---
global:
  serviceAccountName: "dagster"
rbacEnabled: false
imagePullSecrets:
  - name: ger-is-registry
deployments:
  - name: "stary"
    image:
      repository: ger-is-registry.caas.intel.com/qa-platform/tools/stary/stary
      tag: 0.3.3
      pullPolicy: IfNotPresent
    dagsterApiGrpcArgs:
      - "-m"
      - "stary.dagster.definitions"
    port: 4000
    envSecrets:
      - name: stary
    readinessProbe:
      periodSeconds: 20
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
    volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: dagster-logs-pvc
    volumeMounts:
    - name: logs
      mountPath: /compute_logs
serviceAccount:
  create: false