#!/bin/bash

set -e

REPOSITORY=${REPOSITORY:-"qa-platform/tools/stary"}

PROJECT_IMAGE=$PROJECT_NAME:$DOCKER_TAG
REMOTE_PROJECT_IMAGE=$DOCKER_REGISTRY_URL/$REPOSITORY/$PROJECT_IMAGE
docker tag $PROJECT_IMAGE $REMOTE_PROJECT_IMAGE
docker push $REMOTE_PROJECT_IMAGE

docker logout